### ISSUE TITLE
Code for complete

### ISSUE THREAD

**Issue by noorhaq** [lucadentella/esp32s2Stick#3]
Hi in the arduino part I can see the testing codes but not the code, which will actually make it work. Like PC and SD card will be accessible

**Comment by lucadentella** [comment]
Hi! Please consider this project as a "devboard", not a final product. This is the reason why you can't find a code for a specific behavior... you can develop your own code (starting from my example but also using the "plain" esp framework) for your goal. 
I know some users who worked on a code to simulate a keyboard and let the device "type" the content of a file on the SD or other users who implemented a "bridge" between a TCP socket and mouse movements.
