### ISSUE TITLE
Ordered a couple of these from PCBWay, they don't seem to power up

### ISSUE THREAD

**Issue by cieslicki** [lucadentella/esp32s2Stick#4]
Edited: I think I got shipped a bad batch of USB connectors, or there is some PCB trace issue with power coming out of the connector. I soldered jumpers on power and ground to the debug pads, and then also directly to the D+/D- pins coming out of the connector, and it powers up and programs. But then after I program it and plug it back in with the regular connector, it won't power up.

original:

When I plug the device in, there is no indication it is powered up by the LED. Also the voltage regulator is cold. When I attempt to put it into DFU mode with the buttons, the Arduino IDE doesn't see it. I don't think these work at all. Maybe it is an assembly issue.

What is the expected behavior when the device gets plugged in?

**Comment by lucadentella** [comment]
Hi

I only ordered PCBs from PCBWay so I can't tell how good they are in assembling the device. It definetly sounds an issue with their USB connector even if it's a very simple part (compared to the new USB-C connectors)

Let me know how it goes, did you try to replace the connector?

**Comment by cieslicki** [comment]
Hi.

After further investigation I can say it's definitely not the connector that is the source of the problem. 

1) I can plug it in and use a multimeter to read 5v from PWR to GND from the connector pins where they attach to the board.

2) I soldered an external LM1117 voltage regulator onto the debug pads, and ran jumpers back to 5v and GND at the connector pins, the module will power up and program with the board's main USB-A connector plugged into my laptop. So all four connector pins work.

I would say the board at least has power issues. For example, I don't see either a trace or a via at the connector ground pin. So I don't know that the board grounds, and I suspect it does not. I soldered in a jumper from the on-board voltage regulator ground to the connector ground, and it still did not fire up the board, so there are likely a collection of grounding issues.

I tried a couple of different jumper configurations to try to get the on-board voltage regulator to power the module, but nothing I tried worked there.

**Comment by lucadentella** [comment]
Hi

I made a few of these boards (by myself, not using PCBway assembly service) and they work fine.
I also contacted some users which in the past asked me for files... and they also were able to build some boards without issues.

The connector GND pin should be connected via thermals to the ground plane and you should be able to test using a multimeter that it is also connected to other GND pins (regulator, debug...). 

I suspect that something went wrong during the assembly... maybe they used the wrong voltage regulator (which has a different pin layout)? Unfortunately I've no control on what PCBway does (I only uploaded the gerber files for PCB manufacturing).

**Comment by cieslicki** [comment]
Apologies, my error on the grounding. I see now how it grounds.

It actually looks like the voltage regulators on the boards are producing 2.5v, and not 3.3v, which would explain why they don't seem to power up when plugged in, but do power up when I solder on an external known-good 3v3 voltage regulator onto the debug pads.

From the regulator's Vin to GND at the connector pin I read 5v, which is expected and should tell us that the regulator is getting the full 5v from the connector.

However, from the regulator's Vout to GND at the connector, I read 2.4 - 2.5v, depending on which of the several boards I was shipped. 

The regulators on the boards are labeled
BB1117
232GX4H

Reading that datasheet, it looks like BB1117 corresponds to the adjustable voltage version https://www.ti.com/lit/ds/sbvs001d/sbvs001d.pdf?ts=1677173698375&ref_url=https%253A%252F%252Fwww.google.com%252F

The adjustable voltage version uses resistors to set the output voltage, but interestingly none of the specified resistor combinations in the datasheet would produce 2.4-2.5v. I would imagine that you would have originally laid out the board expecting a standard 3.3v regulator?

When I look at the BOM on the order, the voltage regulator is specified as REG1117 (the adjustable voltage part) when I would have expected REG1117-3.3, the 3.3v part.

And, as mentioned, with an external 3.3v regulator attached at debug pads, the board does power and program. 

Maybe this will be a good excuse for me to purchase re-work tools, so I can replace the regulators. 

Thanks for chatting.

**Comment by lucadentella** [comment]
thanks: I confirm that IC1 is a **fixed**, 3.3V regulator
